config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users  do
    get "register", :to => "devise/registrations#new"
    get "sign_in", :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end
  resources :statuses
  get ':id', to: "profiles#show"
  root to:"statuses#index"

  

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 2 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true,
                            uniqueness: true,
                            format: {with: /[a-zA-Z0-9_]+/, messages: 'Must beformatted correctly.'}


  has_many :statuses

  def full_name
    "#{first_name} #{last_name}"
  end
  def gravatar_url
    "http://www.gravatar.com/avatar/#{hash_email}"
  end
  private
  def hash_email
    sanitized_email = email.strip.downcase
    Digest::MD5.hexdigest(sanitized_email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  def devise_parameter_sanitizer
      if resource_class == User
        User::ParameterSanitizer.new(User, :user, params)
      else
        super
      end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content)
    end
end

app/helpers/application_helper.rb
require 'digest/md5'
module ApplicationHelper

  def gravatar_image(email)
    email_hash = hashed_email(email)
    raw("<img src=\"http://www.gravatar.com/avatar/#{email_hash}.jpg\"/>")
  end
  def hashed_email(email)
    email = email.strip.downcase
    Digest::MD5.hexdigest(email)
  end
end 

app/helpers/statuses_helper.rb
module StatusesHelper
  def flash_class(type)
    case type
    when :notice
      "alert-success"
    when :alert
      "alert-error"
    else
      ""
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Treebook', root_path, class: 'brand' %>
        <ul class="nav">
          <li><%= link_to 'All Statuses', statuses_path %></li>
        </ul>
        <ul class="nav pull-right">
         
            <% if user_signed_in? %>
             <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
              <% else %>
              <li><%= link_to 'Register', register_path %></li>  
              <li><%= link_to 'Sign in', sign_in_path %></li>
            <% end %> 
          
        </ul>
    </div>
   </div> 
  </div>
  <div class="container">
     <div class="row">
       <% if flash.any? %>
        <% flash.each do |type, msg|  %>
          <div class="alert <%= flash_class type %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= msg %>
          </div>
        <% end %>
       <% end %>  
     </div><!-- end row -->
  </div><!-- end container -->
<%= yield %>
</div> 
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>
      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> 
  <% end %>
    <%= f.input :content, input_html: { rows: 10, cols: 200} %>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
 <div class="page-header">
  <h1>All of the statuses</h1>
 </div>
 <%= link_to 'Post a New Status', new_status_path, class: 'btn btn-success' %>
<% @statuses.each do |status| %>
<div class="status row">
  <div class="span1">
    <%#= gravatar_image(current_user.email) %>
    <%= image_tag current_user.gravatar_url %>
  </div>
  <div class="span7">
  <strong><%= status.user.full_name %></strong>
  <p><%= status.content  %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + ' ago', status %>  
    <span class="admin">
     | <%= link_to 'Edit', edit_status_path(status) %> |
      <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
  </div>
</div>
</div>
<% end %>
<br>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>